#ifndef SEPIAFILTER_GLOBAL_H
#define SEPIAFILTER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SEPIAFILTER_LIBRARY)
#  define SEPIAFILTERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SEPIAFILTERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SEPIAFILTER_GLOBAL_H
