#ifndef GREYSCALEEFFECT_GLOBAL_H
#define GREYSCALEEFFECT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GREYSCALEFILTER_LIBRARY)
#  define GREYSCALEFILTERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define GREYSCALEFILTERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GRAYSCALEFILTER_GLOBAL_H
